version: "3.8"
services:
  ecommerce-spring:
    image: ecommerce-spring
    build:
      context:
        .
      args:
        - STRIPE_PUBLIC_API_KEY=${STRIPE_PUBLIC_API_KEY}
        - STRIPE_SECRET_API_KEY=${STRIPE_SECRET_API_KEY}
        - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
        - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache

  db:
    image: mysql:8
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"

  cache:
    hostname: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  data: